# Generated by Django 4.1.7 on 2024-02-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_usermodel_userdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
